export const MODULE_NAME = 'menu';

/* GETTERS - START */
const _GETTERS = {
  MENU_ITEMS: 'menuItems',
  DROPDOWN_COUNTRIES: 'dropdownCountries',
  DROPDOWN_LANGUAGES: 'dropdownLanguages',
  DROPDOWN_CURRENCIES: 'dropdownCurrencies',
  DEFAULT_COUNTRY: 'defaultCountry',
  DEFAULT_LANGUAGE: 'defaultLanguage',
  DEFAULT_CURRENCY: 'defaultCurrency',
  SELECTED_COUNTRY: 'selectedCountry',
  SELECTED_LANGUAGE: 'selectedLanguage',
  SELECTED_CURRENCY: 'selectedCurrency',
  SELECTED_CURRENCY_DETAIL: 'selectedCurrencyDetail',
};

export const GETTERS = {
  MENU_ITEMS: `${MODULE_NAME}/${_GETTERS.MENU_ITEMS}`,
  DROPDOWN_COUNTRIES: `${MODULE_NAME}/${_GETTERS.DROPDOWN_COUNTRIES}`,
  DROPDOWN_LANGUAGES: `${MODULE_NAME}/${_GETTERS.DROPDOWN_LANGUAGES}`,
  DROPDOWN_CURRENCIES: `${MODULE_NAME}/${_GETTERS.DROPDOWN_CURRENCIES}`,
  DEFAULT_COUNTRY: `${MODULE_NAME}/${_GETTERS.DEFAULT_COUNTRY}`,
  DEFAULT_LANGUAGE: `${MODULE_NAME}/${_GETTERS.DEFAULT_LANGUAGE}`,
  DEFAULT_CURRENCY: `${MODULE_NAME}/${_GETTERS.DEFAULT_CURRENCY}`,
  SELECTED_COUNTRY: `${MODULE_NAME}/${_GETTERS.SELECTED_COUNTRY}`,
  SELECTED_LANGUAGE: `${MODULE_NAME}/${_GETTERS.SELECTED_LANGUAGE}`,
  SELECTED_CURRENCY: `${MODULE_NAME}/${_GETTERS.SELECTED_CURRENCY}`,
  SELECTED_CURRENCY_DETAIL: `${MODULE_NAME}/${_GETTERS.SELECTED_CURRENCY_DETAIL}`,
};
/* GETTERS - END */

/* ACTIONS - START */
const _ACTIONS = {
  LOAD_MENU_ITEMS: 'loadMenuItems',
  LOAD_GEOIP_CONFIG: 'loadGeoIPConfig',
  LOAD_DROPDOWN_OPTIONS: 'loadDropdownOptions',
};

export const ACTIONS = {
  LOAD_MENU_ITEMS: `${MODULE_NAME}/${_ACTIONS.LOAD_MENU_ITEMS}`,
  LOAD_GEOIP_CONFIG: `${MODULE_NAME}/${_ACTIONS.LOAD_GEOIP_CONFIG}`,
  LOAD_DROPDOWN_OPTIONS: `${MODULE_NAME}/${_ACTIONS.LOAD_DROPDOWN_OPTIONS}`,
};
/* ACTIONS - END */

/* MUTATIONS - START */
const _MUTATORS = {
  SET_MENU_ITEMS: 'setMenuItems',
  SET_DROPDOWN_OPTIONS: 'setDropdownOptions',
  SET_GEOIP_CONFIG: 'setGeoIPConfig',
  SET_SELECTED: 'setSelectedOption',
};

export const MUTATORS = {
  SET_SELECTED: `${MODULE_NAME}/${_MUTATORS.SET_SELECTED}`,
};
/* MUTATIONS - END */

export default {
  _GETTERS,
  _ACTIONS,
  _MUTATORS,
};
