export const MODULE_NAME = 'cart-summary';

/* GETTERS - START */
const _GETTERS = {
  CART_ITEMS: 'cartItems',
  CART_DATA: 'cartData',
  CHECKOUT_STAGE: 'stage',
  PAYMENT_STATUS: 'paymentStatus',
};

export const GETTERS = {
  CART_ITEMS: `${MODULE_NAME}/${_GETTERS.CART_ITEMS}`,
  CART_DATA: `${MODULE_NAME}/${_GETTERS.CART_DATA}`,
  CHECKOUT_STAGE: `${MODULE_NAME}/${_GETTERS.CHECKOUT_STAGE}`,
  PAYMENT_STATUS: `${MODULE_NAME}/${_GETTERS.PAYMENT_STATUS}`,
};
/* GETTERS - END */

/* ACTIONS - START */
const _ACTIONS = {
  LOAD_CART_ITEMS: 'loadCartItems',
};

export const ACTIONS = {
  LOAD_CART_ITEMS: `${MODULE_NAME}/${_ACTIONS.LOAD_CART_ITEMS}`,
};
/* ACTIONS - END */

/* MUTATIONS - START */
const _MUTATORS = {
  ADD_TO_CART: 'addToCart',
  SETUP_CART: 'setupCart',
  UPDATE_CART_STAGE: 'updateStage',
  UPDATE_CART_DATA: 'updateCartData',
  UPDATE_ITEM_STOCK: 'updateItemStock',
  UPDATE_CART_ITEM_QUANTITY: 'updateCartItemQuantity',
  REMOVE_CART_ITEM: 'removeCartItem',
  CLEAR_SHOPPING_CART: 'clearShoppingCart',
  SET_PAYMENT_RESPONSE: 'setPaymentResponse',
  CLEAR_PAYMENT_DATA: 'clearPaymentResponse',
};

export const MUTATORS = {
  ADD_TO_CART: `${MODULE_NAME}/${_MUTATORS.ADD_TO_CART}`,
  SETUP_CART: `${MODULE_NAME}/${_MUTATORS.SETUP_CART}`,
  UPDATE_CART_STAGE: `${MODULE_NAME}/${_MUTATORS.UPDATE_CART_STAGE}`,
  UPDATE_CART_DATA: `${MODULE_NAME}/${_MUTATORS.UPDATE_CART_DATA}`,
  UPDATE_ITEM_STOCK: `${MODULE_NAME}/${_MUTATORS.UPDATE_ITEM_STOCK}`,
  UPDATE_CART_ITEM_QUANTITY: `${MODULE_NAME}/${_MUTATORS.UPDATE_CART_ITEM_QUANTITY}`,
  REMOVE_CART_ITEM: `${MODULE_NAME}/${_MUTATORS.REMOVE_CART_ITEM}`,
  CLEAR_SHOPPING_CART: `${MODULE_NAME}/${_MUTATORS.CLEAR_SHOPPING_CART}`,
  SET_PAYMENT_RESPONSE: `${MODULE_NAME}/${_MUTATORS.SET_PAYMENT_RESPONSE}`,
  CLEAR_PAYMENT_DATA: `${MODULE_NAME}/${_MUTATORS.CLEAR_PAYMENT_DATA}`,
};
/* MUTATIONS - END */

export default {
  _GETTERS,
  _ACTIONS,
  _MUTATORS,
};
